---
title: 假日政策历史回顾
author: Taopj
date: '2021-05-19'
slug: index.zh-hans
showLicense: false
showToc: true
categories:
  - 季节调整
tags:
  - 假日
---

季节调整程序（X13-Arima-AS）需要假日数据，因此，收集了一些建国以来中国假日变化情况历史资料，在此列出。

### 工作时间的规定

一个笼统的说法“1995年5月1日前6天工作制，之后改为每周5天工作制。”  

- 《国务院关于职工工作时间的规定》（中华人民共和国国务院令第146号），1994年2月3日签发（李鹏），自1994年3月1日起施行。（1994年1月24日国务院第15次常务会议通过）
	 > - 第三条 国家实行职工每日工作8小时、平均每周工作40小时的工时制度。
	 > - 第九条 本规定自1994年3月1日起施行。1994年3月1日施行有困难的，可以适当延期，但是最迟不得超过1994年5月1日。

- 《国务院关于修改〈国务院关于职工工作时间的规定〉的决定》(国务院第174号令，1995年3月25日)
	> - 第三条 职工每日工作8小时、每周工作40小时。
	> - 第九条 本规定自1995年5月1日起施行。该日施行有困难的企业、事业单位，可以适当延期，但是事业单位最迟应当自1996年1月1日起施行，企业最迟应当自1997年5月1日起施行。
	
### 放假时间的规定

- 1949年12月23日 《全国年节及纪念日放假办法》（政务院）
全年共7天法定节假日：元旦一天；春节三天；五一国际劳动节一天；国庆两天。
 > 为统一全国之年节及纪念日放假起见，规定下列各项办法： 
	甲、属于全体者 
		一、新年放假一日 一月一日 
		二、春节放假三日 夏历正月初一日、初二日、初三日 
		三、劳动节放假一日 五月一日 
		四、国庆纪念日放假二日 十月一日、二日 
	乙、属于部分人民之节日，为了便于部分人民的群众活动，得放假半天，或只其中一部分人放假，其他一部分人得推代表参加庆祝。 
		一、妇女节（限于妇女）三月八日 
		二、青年节（限于中等学校以上的学生）五月四日 
		三、儿童节 六月一日 
		四、人民解放军建军纪念日（限于军队及军事机关）八月一日 
	丙、其他 
		一、凡属少数民族习惯之假日，由各少数民族集居地区之地方人民政府，斟酌各该民族习惯，规定放假日期。 
		二、其他各种纪念节日如：二七纪念、五卅纪念、七七抗战纪念、八一五抗战胜利纪念、九一八纪念、护士节、教师节、记者节等，均不必放假。（注解：1951年8月13日政务院通告将“八一五抗战胜利纪念日”改为每年九月三日。） 
	丁、凡属于全体之假日，如适逢星期日，应在次日补假。凡属于部分人民之假日，如适逢星期日，则不补假。
	
- 1999年9月18日《国务院关于修改〈全国年节及纪念日放假办法〉的决定》第一次修订（国务院令第270号）
国定假10天，自发布之日起施行：
 > (一)新年,放假1天(1月1日)；
  (二)春节,放假3天(农历正月初一、初二、初三)；
  (三)劳动节,放假3天(5月l日、2日、3日)；
  (四)国庆节,放假3天(10月1日、2日、3日)。
第六条　全体公民放假的假日，如果适逢星期六、星期日，应当在工作日补假。

- 2007年12月14日《国务院关于修改〈全国年节及纪念日放假办法〉的决定》第二次修订（国务院令第513号）
国定假11天，自2008年1月1日起施行：
 >  （一）新年，放假1天（1月1日）；
	（二）春节，放假3天（农历除夕、正月初一、初二）；
	（三）清明节，放假1天（农历清明当日）；
	（四）劳动节，放假1天（5月1日）；
	（五）端午节，放假1天（农历端午当日）；
	（六）中秋节，放假1天（农历中秋当日）；
	（七）国庆节，放假3天（10月1日、2日、3日）。
第六条　全体公民放假的假日，如果适逢星期六、星期日，应当在工作日补假。

- 2013年12月11日《国务院关于修改〈全国年节及纪念日放假办法〉的决定》第三次修订（国务院令第644号）
国定假11天，自2014年1月1日起施行：
> 第二条　全体公民放假的节日：
（一）元旦，放假1天(1月1日)；
（二）春节，放假3天(农历正月初一、初二、初三)；
（三）清明节，放假1天(农历清明当日)；
（四）劳动节，放假1天(5月1日)；
（五）端午节，放假1天(农历端午当日)；
（六）中秋节，放假1天(农历中秋当日)；
（七）国庆节，放假3天(10月1日、2日、3日)。
第六条　全体公民放假的假日，如果适逢星期六、星期日，应当在工作日补假。
